apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: hello-world
---
apiVersion: v1
data:
  helloworld: kwarktasjes
kind: ConfigMap
metadata:
  name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-configmap
  labels:
    app: hello-world-configmap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-configmap
  template:
    metadata:
      labels:
        app: hello-world-configmap
    spec:
      containers:
      - name: hello-world-configmap
        image: "enabledocker/hello-world-configmap:1.0"
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "80"
        - name: HELLOWORLD
          valueFrom:
            configMapKeyRef:
              name: hello-world
              key: helloworld
---
apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: hello-world.part3.xyz-rules
   annotations:
     kubernetes.io/tls-acme: "true"
 spec:
   ingressClassName: nginx
   rules:
  - host: hello-world.part3.xyz
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: hello-world-configmap
             port:
               number: 80
   tls:
   - secretName: hello-world.part3.xyz-tls
     hosts:
     - hello-world.part3.xyz